name: Test

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::539825459646:role/GitHubTerraformDeploy
          role-session-name: terraform-deploy
          aws-region: us-east-1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::690596055674:role/GitHubTerraformDeploy
          role-session-name: terraform-deploy
          aws-region: us-east-1
